### ISSUE TITLE
seoul-2018-1 쿠폰 지원

### ISSUE THREAD

**Issue by keedi** [opencloset/OpenCloset-Coupon-Web#6]
기존 종료된 `seoul-2017-2` 이후 2018년 2월 19일 부터 시작하는 서울시 쿠폰을 지원해야 합니다. 연동과 관련해 자세한 내용은 서울시나 관련 업체로 부터 전혀 전달 받은 것이 없으므로 작년 마지막 쿠폰 내용을 참고해 최대한 유사하게 연동이 가능하도록 합니다.

**Comment by keedi** [comment]
릴리스 및 실서버 배포 완료되었습니다. 이슈 닫습니다.

**Comment by pingpongworks** [comment]
명절연휴에도 불구하고 빠른 작업 해주셔서 감사드립니다. 오픈후에 테스트해본 후 문제 있으면 연락드리겠습니다. 감사합니다. 

연장 관련 등 나머지 부분들은 관련자들과 논의 후 정리해서 다시한번 말씀드리겠습니다.

**Comment by pingpongworks** [comment]
![_20180219_100548_1](https://user-images.githubusercontent.com/17288038/36362152-5ae073aa-1575-11e8-8701-481b3ca24b4f.png)

서울시 예약을 테스트해본 결과, 현재 이런 에러 메시지가 뜨고 있습니다. 검토 부탁드립니다. @keedi

**Comment by pingpongworks** [comment]
홈페이지 업체에 요청하여 
/seoul/2017/2 주소를
/seoul/2018/1 로 수정하여 예약에러 문제 해결하였습니다.

**Comment by pingpongworks** [comment]
현재는 취날 관리자에서 예약내역이 확인되고 있지 않아 확인중입니다. 우리 프로그램 문제는 아닌 듯 하나, 확인후에 이슈 닫겠습니다.

**Comment by pingpongworks** [comment]
열린옷장 프로그램에서 예약 문제 없고, 예약내역도 관리자페이지로 정상 전송되고 있으나
단지, 관리자페이지에서 안 보이는 문제로 판단되어 제작업체에 문제해결 요청중입니다. 
본 이슈와 상관없으므로 이슈 닫겠습니다.

**Comment by pingpongworks** [comment]
관리자페이지에서 예약내역 안 보이는 문제, 해결되었습니다. 자세한 이유는 못 들었고, 처리하였다는 답변만 간단히 메일로 받았습니다. 테스트해보니 현재 문제없습니다.

**Comment by keedi** [comment]
이슈가 릴리스되서 완료될 경우 이슈를 닫습니다. 이 경우는 논의 후 정말 열어야 할 이슈가 아니면 열지 않으시길(re-open) 부탁드립니다. 릴리스되서 완료된 경우 이후 이슈는 **항상** 별도의 상세한 제목으로 이슈를 새로 생성해서 기입 부탁드립니다. 지금도 관련해서 다시 열었던 내용은 별도의 이슈를 열어서 처리해야 할 내용입니다. 관련 없는 내용이 하나의 이슈에 연관해서 달릴 경우 이후 문제의 추적과 해결이 어려워지기 때문입니다. 참고 부탁드립니다.

**Comment by pingpongworks** [comment]
네, 확인했습니다.
